### PR TITLE
Implement interval metrics, Update to .NET 4.8 and fix padding

### PR DESCRIPTION
**Pull request by ghost**
## Fixed right padding (before vs. after)

image

## Interval vs. Time Metrics

image

## Frequency vs. Time Metrics

image

## Other Metrics

Does not show on other modes:

image

### CODE REVIEW

**Comment by amitxv** [comment]
image

**Comment by avendael** [comment]
Please merge. MouseTester is currently broken at the latest windows 11 patch.

**Comment by ghost** [comment]
> Please merge. MouseTester is currently broken at the latest windows 11 patch.

What is broken exactly?

**Comment by avendael** [comment]
> > Please merge. MouseTester is currently broken at the latest windows 11 patch.
> 
> What is broken exactly?

Plots look like this after update:

image

Reverting the update returns plots back to normal.

**Comment by ghost** [comment]
Can you please show the ``Interval vs. Time`` plot? Is it fixed in [this release](https://github.com/amitxv/MouseTester/releases)? Feel free to show the plot for both versions of MouseTester.

**Comment by avendael** [comment]
`Interval vs. Time`

image
image

I had to revert Windows Update KB5022497, KB5025297 and some others that Windows installed in the same day. Not sure which update specifically broke the plots. Issue persists in release `v1.4.5`

image

I'm on Windows 11 22H2 running on Ryzen 5950x. Tried testing with 5 different mice and 2 different mousepads and it's reproducible in all of them.

**Comment by ghost** [comment]
This isn't related to any version of MouseTester. [Windows 11 Moment 3 limits the raw input listening rate for background processes](https://twitter.com/amitxv/status/1666157717759877120?s=20). Although, it should not be taking effect if MouseTester is the foreground process. Was another program the foreground window while you were recording the log?

See: https://blogs.windows.com/windowsdeveloper/2023/05/26/delivering-delightful-performance-for-more-than-one-billion-users-worldwide

**Comment by avendael** [comment]
Thanks for that, now I understand. I was swiping outside of the mousetester window. Clicking inside the window before moving the mouse fixes the issue.

**Pull request closed without merging**
